caminhos = {
    'login': '//*[@id="UserName"]',
    'senha': '//*[@id="Password"]',
    'modulo': '/html/body/div[2]/nav/div[1]/ul/li[1]/div[2]/a',
    'movimentacao': '/html/body/div[1]/div/div/div[2]/div/div/div/div/span',
    'select_mov': '/html/body/div[1]/div/div/div[2]/div/div/div/input[1]',
    'cart1': '/html/body/div[2]/nav/div[1]/ul/li[104]/a/i',
    'cart2': '/html/body/div[2]/nav/div[1]/ul/li[104]/ul/li[1]/a',
    'new': '//*[@id="btnNovo"]',
    'operacao': '/html/body/div[2]/div[1]/div[2]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[1]/div/form/div[1]/div/div/div[2]/select',
    'estoque': '/html/body/div[2]/div[1]/div[2]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[1]/div/form/div[1]/div/div/div[3]/select',
    'participantes': '/html/body/div[2]/div[1]/div[2]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[1]/div/form/div[3]/div/div/div[1]/div/input',
    'numero': '/html/body/div[2]/div[1]/div[2]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[1]/div/form/div[3]/div/div/div[3]/input',
    'produto': '/html/body/div[2]/div[1]/div[2]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[1]/div/table[1]/tbody/tr/th[2]/div[1]/div/input',
    'qnt': '/html/body/div[2]/div[1]/div[2]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[1]/div/table[1]/tbody/tr/th[4]/div/div/input',
    'fp': '/html/body/div[2]/div[1]/div[2]/div[1]/div/div[2]/div[2]/div/div/div/div/ul/li[5]/a',
    'venc': '//*[@id="Vencimento"]',
    'qnt_venc': '//*[@id="Quantidade"]',
    'forma_pgto': '/html/body/div[2]/div[1]/div[2]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[5]/form/table[1]/tbody/tr/td[1]/div/div/span',
    'chose_formapgto': '/html/body/div[2]/div[1]/div[2]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[5]/form/table[1]/tbody/tr/td[1]/div/input[1]',
    'plano_contas': '/html/body/div[2]/div[1]/div[2]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[5]/form/table[1]/tbody/tr/td[5]/div/span/i',
    'plano': '/html/body/div[1]/div/div/div[2]/form/table/tbody/tr/td[1]/div/div/span',
    'chose_plano': '/html/body/div[1]/div/div/div[2]/form/table/tbody/tr/td[1]/div/input[1]',
    'centro_resultado': '/html/body/div[1]/div/div/div[2]/form/table/tbody/tr/td[2]/div/div/span',
    'set_cr': '/html/body/div[1]/div/div/div[2]/form/table/tbody/tr/td[2]/div/input[1]',
    'sair_plano': '/html/body/div[1]/div/div/div[3]/button',
    'save': '/html/body/div[2]/div[1]/div[2]/div[1]/div/div[1]/div[2]/div/div[2]/button'
}


